### ISSUE TITLE
Failing to support alternative Python installation

### ISSUE THREAD

**Issue by olegmikul** [JuliaPy/PyCall.jl#245]
I have installed alternative Python and key dependencies (IPython, PyQT4, numpy, scipy, matplotlib, spyder) in my custom area. Controlling my PYTHONHOME and PYTHONPATH system varialbes I can switch to custom installation and everything from python/IPython/spyder works just fine witn new alternative version. However, when I am using Julia it fails at "using PyCall" operation. It seems it still uses default system Python libraries and dependencies instead of  alternatives. I tryied to use only one change "ENV["PYTHON"]="..." ", also as trying to reproduce  PYTHONHOME and PYTHONPATH within julia but nothing works. 

Please provide support on how to resolve that issue. Thanks!

**Comment by stevengj** [comment]
Do `ENV["PYTHON"]="/path/to/your/python"` and then re-run `Pkg.build("PyCall")`.  Then if you re-launch Julia and do `using PyCall` it should use your new Python.

**Comment by olegmikul** [comment]
It doesn't help. I see the same behavior and for some reason it still calls the default system library of python: 
===
signal (11): Segmentation fault
PyObject_Call at **/usr/lib64/libpython2.7.so** (unknown line)
===

**Comment by stevengj** [comment]
@olegmikul, I'm a little confused.   Try:
```jl
pyconfigvar(python::AbstractString, var::AbstractString) = chomp(readall(`$python -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('$var'))"`))
pyconfigvar("/path/to/my/python2.7.11", "LDLIBRARY")
pyconfigvar("/path/to/my/python2.7.11", "LIBDIR")
```
This queries your Python's `sysconfig` module for the libpython library name and path.  Is it returning the correct library?

**Comment by lewisl** [comment]
I am having the same problem.  On Mac Sierra with Julia 0.5.0.  

Recommendation to set ENV["Python"] and rebuild does not work.

I should never get a new computer.  Hours lost getting config state replicated.  Fragile stuff that seems to never get fully solved.

I guess I'll do the usual and wipe away Julia and start over again.

**Comment by lewisl** [comment]
I am stumped.  I have purged all of Julia and dependencies.  Reinstalled.

Initialized package dir with Pkg.status().

Clean install of PyCall with Pkg.add("PyCall").

In my bash profile I have:
# Setting PATH for Python 3.5
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"
export PATH

alias python='python3'
alias pip='pip3' 

For good measure I have a symlink at /usr/local/bin/python which points to the Python 3.5 executable.

No go.

It's something simple but never simple to find.

**Comment by stevengj** [comment]
What is the output of `Pkg.build("PyCall")`?

**Comment by lewisl** [comment]
A clue:  PyCall always uses /usr/bin/python.  And "which python" also always returns /usr/bin/python.

Output of Pkg.build("PyCall"):

INFO: Building Conda
INFO: Building PyCall
INFO: PyCall is using /usr/bin/python (Python 2.7.10) at /usr/bin/python, libpython = /System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7

So, I need to get the system to point to another Python because the Julia environment variable seems to be ignored by Pkg.build...

**Comment by lewisl** [comment]
A bit of progress though no solution.

which python now reports the python instance that is python 3.5:

`lewis2016macbookpro:bin lewis$ which python
/Library/Frameworks/Python.framework/Versions/3.5/bin/python
lewis2016macbookpro:bin lewis$ `

This required a different pattern of symlinks.  There is now a symlink usr/local/bin to the python in /library/frameworks/python.framework/versions/3.5/bin.  It was important that the target in this framework version be called "python".   The target is a symlink to the yet another symlink to the actual 3.5 binary.

So, I thought this would trick the PyCall build process:  when it searched for the current python on the system, it should find the same python as if it were doing "which python".

This didn't work.  But, I didn't manually set ENV["Python"].  So, now I will try somewhat different targets for this variable.

By, the way:  I am diagnosing this by looking at another Mac which doesn't have the PyCall build problem: never did--it always just worked.  On the new Mac, I initially did nothing special:  std. install of Julia 0.5.0, std install (from Python.org) of Python 3.5.  But, the pattern of symlinks for Python on the new machine was different than my old machine.  I DON'T think this has anything to do with Sierra (I am running it on both machines).  I think the difference probably comes from changes in the Python installer:  I am installing a new version of Python and I am targeting 3.5 as my default Python.

Finally making the Python changeover.  I'm out of excuses.  print() for me from now on.

**Comment by lewisl** [comment]
I am probably wrong but it seems like the build code for PyCall simply ignores ENV["Python"] or is getting the target from some other secret config information.  Not sure what else I can provide by way of diagnosis.

Here are two experiments setting the target for the ENV variable slightly differently with neither working:

`shell> which python
/Library/Frameworks/Python.framework/Versions/3.5/bin/python

julia> ENV["Python"] = "/Library/Frameworks/Python.framework/Versions/3.5/bin/python"
"/Library/Frameworks/Python.framework/Versions/3.5/bin/python"

julia> Pkg.build("PyCall")
INFO: Building Conda
INFO: Building PyCall
INFO: PyCall is using /usr/bin/python (Python 2.7.10) at /usr/bin/python, libpython = /System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7

shell> stat "/Library/Frameworks/Python.framework/Versions/3.5/bin/python"
16777220 1949730 lrwxr-xr-x 1 lewis admin 0 11 "Nov 19 09:40:26 2016" "Nov 19 09:40:26 2016" "Nov 19 09:40:26 2016" "Nov 19 09:40:26 2016" 4096 8 0 /Library/Frameworks/Python.framework/Versions/3.5/bin/python

julia> ENV["Python"] = "/Library/Frameworks/Python.framework/Versions/3.5/Python"
"/Library/Frameworks/Python.framework/Versions/3.5/Python"

julia> Pkg.build("PyCall")
INFO: Building Conda
INFO: Building PyCall
INFO: PyCall is using /usr/bin/python (Python 2.7.10) at /usr/bin/python, libpython = /System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7`

**Comment by lewisl** [comment]
Glory be!  It worked.  After the system config changes I made, I did not purge and reinstall Julia.  So, I did.  And it worked.  So my latest (possibly incorrect) theory is that wherever the build script for PyCall caches the location of the python library module, it ALWAYS uses that cached location and seemingly ignores any new attempt to set ENV["Python"] before rebuilding.

Here is the output:
`julia> Pkg.init()
INFO: Initializing package repository /Users/lewis/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl

julia> Pkg.add("PyCall")
INFO: Cloning cache of BinDeps from https://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of Compat from https://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of Conda from https://github.com/JuliaPy/Conda.jl.git
INFO: Cloning cache of JSON from https://github.com/JuliaIO/JSON.jl.git
INFO: Cloning cache of MacroTools from https://github.com/MikeInnes/MacroTools.jl.git
INFO: Cloning cache of PyCall from https://github.com/JuliaPy/PyCall.jl.git
INFO: Cloning cache of SHA from https://github.com/staticfloat/SHA.jl.git
INFO: Cloning cache of URIParser from https://github.com/JuliaWeb/URIParser.jl.git
INFO: Installing BinDeps v0.4.5
INFO: Installing Compat v0.9.4
INFO: Installing Conda v0.4.0
INFO: Installing JSON v0.8.0
INFO: Installing MacroTools v0.3.2
INFO: Installing PyCall v1.7.2
INFO: Installing SHA v0.3.0
INFO: Installing URIParser v0.1.6
INFO: Building Conda
INFO: Building PyCall
INFO: PyCall is using python (Python 3.5.2) at /Library/Frameworks/Python.framework/Versions/3.5/bin/python, libpython = /Library/Frameworks/Python.framework/Versions/3.5/lib/libpython3.5m
INFO: Package database updated

julia> 
`

**Comment by stevengj** [comment]
Environment variables are case-sensitive.  You need `ENV["PYTHON"]`, not `ENV["Python"]`.

**Comment by achimnol** [comment]
I have encountered the same problem, and here I share my solution:

 * I'm using Python 3.6 built using homebrew libraries and git-cloned pyenv on macOS Sierra.
 * I have installed matplotlib, numpy, etc. in a virtual environment created using `python -m venv` command.
 * After activating the virtualenv, I installed Julia by `brew cask install julia`.
 * Set environment variable: `export PYTHON=/.../venv/bin/python`
 * Here, just doing `Pkg.add("PyCall")` inside Julia does not work:
   - `/.../venv/bin/python` is actually Python 3.6.0 but it links to `libpython` provided by macOS Sierra, which is 2.7.10.
   - Importing/using `PyPlot` breaks.

```
julia> Pkg.add("BinDeps")
INFO: Installing BinDeps v0.4.7
INFO: Installing PyCall v1.10.0
INFO: Building Conda
INFO: Building PyCall
INFO: PyCall is using /.../venv/bin/python (Python 2.7.10) at /../venv/bin/python, libpython = libpython
INFO: /Users/joongi/.julia/v0.5/PyCall/deps/deps.jl has been updated
INFO: /Users/joongi/.julia/v0.5/PyCall/deps/PYTHON has been updated
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of BinDeps
INFO: Use `Pkg.update()` to get the latest versions of your packages
```

 * To fix the problem:
   - I rebuilt Python 3.6.0 using pyenv by setting `export PYTHON_CONFIGURE_OPTS="--enable-framework"`. (I didn't have to recreate the virtualenv though)
   - Set environment variable: `export LD_LIBRARY_PATH=/Users/joongi/.pyenv/versions/3.6.0/lib/lib` (the location where `libpython3.6m.dylib` exists.)
   - Set environment variable: `export PYTHON=/.../venv/bin/python`
   - Run Julia again and `Pkg.build("PyCall")`. Now it recognizes Python correctly and PyPlot works as expected.

```
julia> Pkg.build("PyCall")
INFO: Building Conda
INFO: Building PyCall
INFO: PyCall is using /.../venv/bin/python (Python 3.6.0) at /.../venv/bin/python, libpython = libpython3.6m
INFO: /Users/joongi/.julia/v0.5/PyCall/deps/deps.jl has been updated
INFO: /Users/joongi/.julia/v0.5/PyCall/deps/PYTHON has been updated
```

I hope that future PyCall.jl versions would improve the discovery of library path. 😃

**Comment by stevengj** [comment]
If Python isn't built as a framework, I don't know if it is possible to link to it on MacOS.

I don't understand what happened when you didn't set LD_LIBRARY_PATH.   What happens when you didn't do that?

**Comment by achimnol** [comment]
@stevengj In my comment above, I have described what happened when I did not set LD_LIBRARY_PATH already. It imports macOS Sierra's `libpython` instead of my pyenv-installed Python's `libpython3.6m`, even though I have set PYTHON environment variable to my virtualenv's executable path where the virtualenv was created from my pyenv-installed Python.

**Comment by lewisl** [comment]
I started this a long time ago and it occasionally pops up again.  I recently bit the bullet and installed Python 3.6 and PyCall wouldn’t find it and installed the not-so mini-conda Python. It should have found it as it is my system python, but here is a very easy way to fix that.

I tried to set ENV[“PYTHON”] to the right place in my frameworks on MacOS Sierra, but I always forget where to aim.  Turns out there is an easy answer. First, if you type python at any terminal prompt and if you get the python you want this means you have the right symlink—probably in /usr/local/bin—which is where it should be.  You can confirm with "which python".  Just set ENV[“PYTHON”] to the path to that symlink (the file itself) or any other python symlink in /usr/local/bin that you want and that you confirm works (and where you pip your packages).  This works perfectly with Pkg.build(“PyCall”) and its simple.  You still need the Conda package, but you don’t need a “private” python.

By the way, a “standard” installation of the miniconda python in conda deps is 1.4G!  Whoa!  Since I use Python for other things, I like to use a standard Python and pip all the stuff I need.  But, since I’ve been doing much more Julia coding of late I am primarily using Python as a dependency for PyPlot and IJulia.  So, I pip numpy, matplotlib, and jupyter, which all bring in lots of their needed dependencies.  But, the whole lot is 420M—less than a third of what conda brings in.  And you know where it is and you know how to manage it—if you are even a basic python user.  If you are not a python user at all, then what PyCall does for you is a fine solution.

By the way no. 2, IJulia is working pretty well these days.  I have a 200+ cell report with data cleansing and some simple stats and a bunch of charts I did with Julia and jupyter.  It used to break. Now, I start up jupyter notebook from Julia, load the notebook, and run all cells and lickity-split the whole sloppy monster (my fault) runs all the way through in no time.  I kinda wish Julia had better stats, with more of a package feel like R (especially in the gorgeous R Studio) but now I am forced to actually remember how to do stuff and right a teeny bit of code to do it.

All in all, I am now a happy camper while 2 years ago I was a grumpy camper.


On Mar 6, 2017, at 8:32 PM, Joongi Kim <notifications@github.com<mailto:notifications@github.com>> wrote:


@stevengj<https://github.com/stevengj> In my comment above, I have described what happened when I did not set LD_LIBRARY_PATH already. It imports macOS Sierra's libpython instead of my pyenv-installed Python's libpython3.6m, even though I have set PYTHON environment variable to my virtualenv's executable path where the virtualenv was created from my pyenv-installed Python.
