### ISSUE TITLE
PyCall Environment for Travis

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPy/PyCall.jl#390]
For PyDSTool.jl, the setup

```julia
env:
   - PYTHON=""
```

is required in Travis for the build to work. While this isn't awful and it doesn't seem to harm the installation for users, this makes it difficult for people to see why the builds are failing when the first add DifferntialEquations/PyDSTool as a dependency. I was wondering if this could be fixed by doing the installation differently? The build.jl file is really simple:

https://github.com/JuliaDiffEq/PyDSTool.jl/blob/master/deps/build.jl

**Comment by stevengj** [comment]
It's not clear to me why you do a build script at all.  You should really just do

`pyimport_conda("PyDSTool", "pydstool", "conda-forge")`

in your module `__init__` instead of `pyimport`.  (Won't conda install scipy automatically if it is a dependency of pydstool?)

The `pyimport_conda` will automatically print a warning suggesting re-building PyCall with `PYTHON=""`.   It will also work with a standard Anaconda install rather than Conda.jl.

As for Travis, I don't know.  I don't think that PyDSTool should be re-configuring PyCall automatically, and short of that I don't see a solution.

**Comment by ChrisRackauckas** [comment]
Thanks for the input. Updated the `init`, got rid of the build, and will keep the ENV change.
