### ISSUE TITLE
implement Python comparison operations

### ISSUE THREAD

**Issue by bbrunaud** [JuliaPy/PyCall.jl#403]
Hello. I'm trying to use a python function that receives a boolean expression. 

Python code
``` 
from z3 import *
x = Real('x')
s = Solver('x')
s.add(x > 5)
```

Julia code
```
@pyimport z3
x = z3.Real("x")
s = z3.Solver()
s[:add](x > 5)
```

Error
```
ERROR: MethodError: no method matching isless(::Int64, ::PyCall.PyObject)
Closest candidates are:
  isless(::Real, ::AbstractFloat) at operators.jl:41
  isless(::Real, ::Real) at operators.jl:75
  isless(::Integer, ::Char) at deprecated.jl:49
 in >(::PyCall.PyObject, ::Int64) at ./operators.jl:64
```

Is there a way to work around this?

thank you!

**Comment by stevengj** [comment]
The problem is that you want to evaluate `x > 5` using the Python `>` operator, not the Julia `>`.  Try, for example:
```
@pyimport z3
x = z3.Real("x")
s = z3.Solver()
s[:add](py"$x > 5")
```
However, I really should implement `<` etcetera for `PyObject` by calling [PyObject_RichCompare](https://docs.python.org/3/c-api/object.html#c.PyObject_RichCompareBool), so that examples like `x < 3` work as-is.

**Comment by stevengj** [comment]
`>` should be implemented now for Python objects in the latest PyCall master.
