### ISSUE TITLE
Memory leak when iterating over collections in a loop

### ISSUE THREAD

**Issue by christopher-dG** [JuliaPy/PyCall.jl#436]
It looks like in some packages, garbage collection is not occurring when it should when repeatedly iterating over collections returned by Python methods. The following code steadily increases memory usage by ~1MB per few seconds:
```
# v0.6.0

julia> using YAML, PyCall

julia> @pyimport praw

julia> bot = praw.Reddit(; map(pair -> Symbol(pair.first) => pair.second, YAML.load(open("config.yml"))["reddit"])...)
PyObject <praw.reddit.Reddit object at 0x7f8bf61d0630>

julia> subreddit = bot[:subreddit]("rarepuppers")
PyObject Subreddit(display_name='rarepuppers')

julia> while true
         for post in subreddit[:new]() end
         sleep(1)
       end
```

Manually calling `gc` cleans up properly, but I don't think that should be necessary...

In the example above, the collection is a Python generator yielding `PyObjects`, but leaks can also happen when the collection and its contents are native Julia objects.

I've reproduced this with `PRAW` on Python 3.4 and 3.6 (both manually installed) and 2.7 (via `Conda.jl`), as well as with `gmusicapi` on 3.6.

I got the memory usage numbers by looking at `top`, there is probably a better way for me to demonstrate the increase though.

**Comment by cortner** [comment]
I can confirm similar behaviour in [this gist](https://gist.github.com/cortner/03e0a670b257685e1a4b8774b0f0efda). : this is unfortunately a very convoluted dependency between a Julia module a large python library and a C code. The offending Julia line (in the Julia library is) 
```
   results = pycall(matscipy_neighbours.neighbour_list,
                     NTuple{length(quantities), PyArray}, quantities,
                     pyobject(atoms), cutoff)
```
An interesting aspect is that sometimes it won't segfault but instead get an error message (from the C library) that shows the string `quantities` has been corrupted.

If I manually add a `gc()` before the offending `pycall`, the problem disappears. It even seems to be sufficient to call `gc()` "every so often", in fact even `rand() < 0.01 && gc()` is enough but it is probably just chance then.

I am fairly certain that in our case the problem is `PyCall` since an equivalent Python code does not segfault. I our case this only seems to happen with Python 3.x.

**Comment by stevengj** [comment]
If calling `gc()` cleans up properly, then it isn't a memory leak — Julia knows how to dispose of the memory.

The problem is just that it isn't garbage-collecting frequently enough for you?

If you have problems even with native Julia objects, then it sounds like this is unrelated to PyCall.

**Comment by stevengj** [comment]
If you have a native-Julia test case where garbage-collection is happening too infrequently, you could submit it as a Julia issue.
