### ISSUE TITLE
[Feature request] Integrate Python docstrings with Julia help

### ISSUE THREAD

**Issue by malmaud** [JuliaPy/PyCall.jl#46]
Not sure how implausible this is, but it would be great if typing
?[python function] 
at the julia REPL gave back the docstring of that function/module, just as IPython's ? does.

**Comment by kskyten** [comment]
This is now possible with the [`@doc` macro](http://docs.julialang.org/en/stable/manual/documentation/). Is it possible to apply this to the methods of an object also so that `? object[:method]` would provide something useful?

**Comment by stevengj** [comment]
@MichaelHatherly, I can't figure out how to hook into the `@doc` macro so that it calls a custom lookup function for a `PyObject`.

Ideally, it would be enough to just define a `Base.Docs.doc(o::PyObject)` method (and, in fact, I currently define such a method), but this doesn't work because `doc` is only called with a `Binding` object.

Does a hook function need to be added to Base.Docs for custom (lazy) docstring lookup?

**Comment by MichaelHatherly** [comment]
> Does a hook function need to be added to Base.Docs for custom (lazy) docstring lookup?

Something like that might work. I'm not all that familiar with PyCall though, so couldn't say for certain.

**Comment by stevengj** [comment]
The point is that for `o::PyObject`, there is a function `doc(o)` to that returns a help string at runtime.  Is there any way to fix `Base.Docs` so that this or a similar method could be called when you do `?o`?

**Comment by MichaelHatherly** [comment]
In that case, yes we'd need to add support for that in `Base.Docs`. I've not got much time at the moment to work on this myself at present though.

**Comment by malmaud** [comment]
OK, we can do this now!

**Comment by stevengj** [comment]
Awesome, thanks for getting this in!
