### ISSUE TITLE
Unnecessary copying on Windows?

### ISSUE THREAD

**Issue by logicchains** [JuliaPy/PyCall.jl#643]
The operation timed below runs in around ten milliseconds for me:

    py"
    import torch
    import datetime
    import numpy as np

    a = np.zeros([64,2,4,128,64])
    pta = torch.from_numpy(a)

    bef = datetime.datetime.now()
    for i in range(0, 100):
        pta.cuda()
    print((datetime.datetime.now() - bef) / 100)
    "
(Prints `0:00:00.009891`)

Equivalent code when run from Julia directly, however, is much slower:

    a = np.zeros([64,2,4,128,64])
    pta = pt.from_numpy(a)
    @BenchmarkTools.btime pta[:cuda]();

gives `134.753 ms (5 allocations: 192 bytes)`

Interestingly, bypassing numpy is much faster:

    ptz = pt.zeros(64,2,4,128,64)
    @time ptz[:cuda]();
Gives around 5 milliseconds.

Any idea why this might be? I don't see the same issue on Linux. I'm using Julia 1.1, PyCall v1.18.5.

**Comment by stevengj** [comment]
`np.zeros([64,2,4,128,64])` converted the result back to a native Julia array.  And then `pt.from_numpy(a)` converts the result back to a Python array before calling `from_numpy`.  This changes the memory layout from row-major to column-major, which changes the timing — probably the `cuda` function is optimized for row-major layout since that is the default in NumPy.

You can keep `a` as a Python-native array by doing `pycall(np.zeros, PyObject, [64,2,4,128,64])` instead.
