### ISSUE TITLE
pyimport syntax: from <module> import <symbol>

### ISSUE THREAD

**Issue by cncastillo** [JuliaPy/PyCall.jl#66]
Maybe in @pyimport macros you could add some other sintaxis, for example if the user dont need to load all the package and only one function or more of it:

```
@pyimport from numpy import zeros, array, fromtxt
@pyimport from mayavi import mlab
@pyimport from scipy.ndimage import gaussian_filter as filter
```

**Comment by marius311** [comment]
Obviously this is 2 years old, but maybe something has changed since then that warrants adding this? I think it'd be a great feature. I don't have concrete examples to add, just to say that obviously it would allow writing more concise easier-to-read code in many cases. 

As for overwriting, once I've written `@pyimport numpy: zeros` doesn't that mean I *want* the overwriting to happen? Its not like it'd be unexpected in some way.

**Comment by stevengj** [comment]
Honestly, I'm thinking of getting rid of `@pyimport` completely, and telling people to just do `numpy = pyimport("numpy")`.   The reason is that it is confusing that you can use `.` to get the members of a `@pyimport` module, but for everything else you need `foo[:bar]`.

You can still just do `z = pyimport("numpy")[:zeros]`, so a Pythonic syntax doesn't actually give you any new functionality.

**Comment by cstjean** [comment]
> I would prefer to use the Julian syntax here (when in Rome...): @pyimport numpy: zeros, array, fromtxt etcetera.

I implemented it in ScikitLearn:

```julia
using ScikitLearn.Skcore: @pyimport2
@pyimport2 scipy.ndimage: (gaussian_filter, fourier_uniform)
```

but I struggled to get the hygiene right. I can make a PR for it if there is interest. 

> Honestly, I'm thinking of getting rid of @pyimport completely, and telling people to just do numpy = pyimport("numpy"). 

-1 for me, that would get tiring.

**Comment by marius311** [comment]
Thanks guys, yea `@pyimport2` is exactly what I'm looking for, helpful to know that's there. 

Re: removing @pyimport completely, its true its slightly inconsistent that you get to use the dot notation for the first level, but honestly as a user that was pretty easy to figure out from skimming your docs and trying a few simple examples. For me it'd seem to be sacrificing too much convenience in the name of consistency. My own +1, as you could probably guess, would instead be incorporating `@pyimport2` into PyCall.
