### ISSUE TITLE
Python.jl REPL no longer working

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaPy/PyCall.jl#662]
This isn't my package, but I was looking into how to fix it.

https://github.com/229668880/Python.jl/blob/e75a761a01f40fd15e47579d4d2ef564d4f73a84/src/Python.jl#L19

[Is it for sure the best idea to deprecate the old syntax, and not just keep both available for old packages such as this one?]

It seems worthwhile to have this package (or maybe its REPL included in PyCall?). My PR and issues there have been ignored, so even if I figure out a fix it seems like I need to fork the package.

I've tried to fix the line locally (or get to work as is with changing the local REQUIRE line to "PyCall 0.18.0 0.18.1"):

to new syntax: pymain.juliatemp= ... but I suppose it only works with already defined.

I've also tried to get an old PyCall to use:

`Pkg.add(PackageSpec(name="PyCall", version="0.18.0"))`  # does this mean at least version, as ]st seems to indicate I have 0.90.0.

**Comment by stevengj** [comment]
It seems like you are running into the change from #638 — there is now a per-module namespace, different from `__main__`, as is documented in the PyCall README.

Not sure why you don't just do
```jl
py"""
import matplotlib.pyplot as plt
from matplotlib.pylab import *
plt.ion()
"""
```
rather than the circumlocution with `exec`.

The Python.jl package was never registered and seems unmaintained, so it's not surprising that it is broken.
